version: '3.8'
services:
  app:
    image: gradle:8.0.2-jdk17
    volumes:
      - .:/app
      - ./build:/app/build
    working_dir: /app
    command: ["gradle", "run", "--no-daemon"]
    ports:
      - "8080:8080"

  test:
    image: gradle:8.0.2-jdk17
    volumes:
      - .:/app
    working_dir: /app
    command: ["gradle", "test", "--no-daemon"]
    # No need for ports in test

# docker-compose down
# docker-compose up
# docker-compose run --rm test gradle test --stacktrace
