-- Sample data for testing (optional)
-- INSERT INTO users (username, email, first_name, last_name, created_at) VALUES
-- ('admin', 'admin@example.com', 'Admin', 'User', NOW()),
-- ('testuser', 'test@example.com', 'Test', 'User', NOW());
